//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Automation.Models
{
    using System;
    
    public partial class ListOfSenders_Result1
    {
        public int id { get; set; }
        public string username { get; set; }
        public bool seenStatus { get; set; }
    }
}
